### PR TITLE
Implement PHP Version dependent deprecations for constants

### PR DESCRIPTION
**Pull request by staabm**
as discussed in https://github.com/phpstan/phpstan-deprecation-rules/pull/112#discussion_r1510222468 with this PR we strip the `@deprecated` phpdoc tag on constant definitions, in case the current php version does not match the declared min version.

motivation: report deprecation errors for constants only when the phpversion matches the `@deprecated $version`  we find in the jetbrains/phpstorm-stubs

example: https://github.com/JetBrains/phpstorm-stubs/blob/9608c953230b08f07b703ecfe459cc58d5421437/filter/filter.php#L478

### CODE REVIEW

**Comment by staabm** [comment]
I was not able to properly run the unit tests locally. not sure how to run them as they seem to expect transformed code (with adjusted namespaces)

**Comment by ondrejmirtes** [comment]
Please send this to Roave/BetterReflection first.

**Comment by staabm** [comment]
it landed in https://github.com/Roave/BetterReflection/pull/1396. do I need to re-submit a PR here, or do you pick the commit from upstream?

**Comment by ondrejmirtes** [comment]
When updating BetterReflection I rebase this fork on top of the latest release.

**Pull request closed without merging**
