### PR TITLE
Only check stub version compatability for core extensions

### PR DESCRIPTION
**Pull request by rvanvelzen**
See phpstan/phpstan#4095 and JetBrains/phpstorm-stubs#957

### CODE REVIEW

**Comment by rvanvelzen** [comment]
I haven't had time to add tests, but I'd rather wait until you confirm that this is a reasonable approach

**Comment by ondrejmirtes** [comment]
Hi, yeah, this is really nice! How did you figure out what's a core extension and what isn't?

There's already some scaffolding for these kind of tests in PhpStormStubsSourceStubberTest (dataMethodSinceVersion, dataFunctionSinceVersion), so add some examples in there, for example for the `newrelic_record_datastore_segment` function.

Don't worry about the build failures, it's sufficient if `vendor/bin/phpunit` passes for you locally. CI pipeline here isn't in a great state, I'm mostly checking manually the failures before tagging a release to see if it's safe or not.

**Comment by rvanvelzen** [comment]
> Hi, yeah, this is really nice! How did you figure out what's a core extension and what isn't?

The stubs don't really provide this information unfortunately. PhpStorm has a built-in list of extensions (categorized by "core", "bundled", "external", "pecl", and "others") of which I included the first 3 categories. Then I checked the remaining extensions on php.net.

> There's already some scaffolding for these kind of tests in PhpStormStubsSourceStubberTest (dataMethodSinceVersion, dataFunctionSinceVersion), so add some examples in there, for example for the newrelic_record_datastore_segment function.

Done :+1:

**Comment by ondrejmirtes** [comment]
Thank you!

**Pull request merged**
