### PR TITLE
fix: ReflectionAttribute::newInstance() with nested class using named arguments

### PR DESCRIPTION
**Pull request by enumag**

### CODE REVIEW

**Comment by enumag** [comment]
Okay it passed now locally. Ideally this should be tested in CompileNodeToValueTest as well but I'm unsure how to write that test.

**Comment by ondrejmirtes** [comment]
Merged as https://github.com/ondrejmirtes/BetterReflection/commit/8d751dd38f4d089715e748863d0d8e4113bc408c, thank you.

**Comment by enumag** [comment]
Thanks! Should the fix be contributed to Roave as well? 🤔 I'm unsure what's the difference between Roave/BetterReflection and your fork.

**Comment by ondrejmirtes** [comment]
There's no code about this in Roave, their `newInstance` method just throws an exception. They don't want to touch autoloading and actually creating the objects with a 100-feet pole.

**Pull request closed without merging**
